language: python
python: 
  - 3.8

install:
  - pip install pipenv

script:
  - echo "skipping tests..."
  - pipenv run pip install -r <(pipenv lock -r) --target _build/app
  - cp -R app/* _build
  - zip -r build.zip _build

deploy:
  provider: lambda
  function_name: "movies"
  region: "eu-central-1"
  role: "arn:aws:iam::419870347460:role/service-role/movies-role-j9ucmxre"
  runtime: "python3.8"
  zip: "./build.zip"
  handler_name: "handler"
